version: '3.1'

services:

  dpg-cf03u682i3mmhme099mg-a.oregon-postgres.render.com:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: db_contact_book

  crud-spring:
    image: crud-spring
    container_name: crud-spring
    ports:
      - 8081:8081
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - dpg-cf03u682i3mmhme099mg-a.oregon-postgres.render.com